# Done to increase performance of Gradle builds
org.gradle.jvmargs=-Xmx3G

# Fabric Properties
minecraft_version=26.1.2
yarn_mappings=26.1.2+build.1
loader_version=0.16.14

# Mod Properties
mod_id=alpaka
mod_name=Alpaka Addons
mod_version=1.0.23
maven_group=net.alpaka.addons

# Dependencies (Fabric API)
fabric_version=0.155.2+26.1.2

# Loom Options
fabric.loom.disableObfuscation=true
